# Generated by Django 5.2.1 on 2025-05-21 16:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="patient",
            old_name="name",
            new_name="full_name",
        ),
        migrations.RemoveField(
            model_name="patient",
            name="age",
        ),
        migrations.AddField(
            model_name="patient",
            name="birth_date",
            field=models.DateField(default="2000-01-01"),
        ),
    ]
