# Generated by Django 5.2.1 on 2025-05-25 13:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_rename_name_patient_full_name_remove_patient_age_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="medicalreport",
            name="content",
            field=models.TextField(default="غير محدد"),
        ),
        migrations.AddField(
            model_name="medicalreport",
            name="is_archived",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="medicalreport",
            name="record",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reports",
                to="core.medicalrecord",
            ),
        ),
    ]
