# Generated by Django 5.2.1 on 2025-05-28 16:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0004_appointment_notes_alter_appointment_patient_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="vitalsign",
            name="unit",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="vitalsign",
            name="patient",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="vitals",
                to="core.patient",
            ),
        ),
    ]
