# Generated by Django 5.2.1 on 2025-05-28 16:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0005_vitalsign_unit_alter_vitalsign_patient"),
    ]

    operations = [
        migrations.AddField(
            model_name="medicalalert",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="medicalalert",
            name="patient",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="alerts",
                to="core.patient",
            ),
        ),
    ]
