# Generated by Django 5.2.1 on 2025-05-28 16:41

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0006_medicalalert_is_active_alter_medicalalert_patient"),
    ]

    operations = [
        migrations.AddField(
            model_name="medication",
            name="end_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="medication",
            name="start_date",
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="medication",
            name="patient",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="medications",
                to="core.patient",
            ),
        ),
    ]
